# Generated by Django 5.1.3 on 2024-11-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registration_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='umail',
            new_name='email',
        ),
    ]
