# Generated by Django 5.1.2 on 2024-11-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_data',
        ),
    ]
